networks:
  route1_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
  route8_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.8.0/24
  route9_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.9.0/24

services:
  host4:
    build:
      context: .
      dockerfile: ./host/dockerfile
    command: tail -f /dev/null
    privileged: true
    networks:
      route9_network:
        ipv4_address: 192.168.9.2

  host5:
    build:
      context: .
      dockerfile: ./host/dockerfile
    command: tail -f /dev/null
    privileged: true
    networks:
      route8_network:
        ipv4_address: 192.168.8.2

  router1:
    build:
      context: .
      dockerfile: ./host/dockerfile
    command: tail -f /dev/null
    privileged: true
    networks:
      route1_network:
        ipv4_address: 192.168.1.254
      route9_network:
        ipv4_address: 192.168.9.254

  router2:
    build:
      context: .
      dockerfile: ./host/dockerfile
    command: tail -f /dev/null
    privileged: true
    networks:
      route1_network:
        ipv4_address: 192.168.1.253
      route8_network:
        ipv4_address: 192.168.8.254